-- Migration: Add is_public field to workout_templates and seed research-backed default templates
-- Date: 2025-01-21
-- Based on: StrongLifts 5x5, Push/Pull/Legs Split, HIIT protocols, and expert-recommended programs

-- Add is_public column to workout_templates
ALTER TABLE workout_templates
ADD COLUMN is_public BOOLEAN DEFAULT FALSE NOT NULL;

-- Create index for public templates
CREATE INDEX idx_workout_templates_public ON workout_templates(is_public) WHERE is_public = TRUE;

-- Create a system user for public templates (using a fixed UUID)
-- Note: This user won't actually exist in auth.users, but we'll use NULL for user_id for system templates
ALTER TABLE workout_templates
ALTER COLUMN user_id DROP NOT NULL;

-- Seed research-backed public workout templates
INSERT INTO workout_templates (user_id, name, description, exercises, is_public) VALUES

-- STRONGLIFTS 5x5 PROGRAM (Research-backed for strength & muscle building)
(
  NULL,
  'StrongLifts 5x5 - Workout A',
  'Classic StrongLifts 5x5 Program - Workout A. Proven strength building program with compound lifts. 5 sets of 5 reps with progressive overload.',
  '[
    {
      "name": "Barbell Squat",
      "exercise_type": "strength",
      "sets": 5,
      "reps": 5,
      "weight": 60,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Start with empty bar if beginner. Add 2.5kg each workout. Rest 3-5 minutes between sets."
    },
    {
      "name": "Bench Press",
      "exercise_type": "strength",
      "sets": 5,
      "reps": 5,
      "weight": 40,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Lower bar to chest, full range of motion. Add 2.5kg each workout."
    },
    {
      "name": "Barbell Row",
      "exercise_type": "strength",
      "sets": 5,
      "reps": 5,
      "weight": 35,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Pull to lower chest, squeeze shoulder blades. Keep back straight."
    }
  ]'::jsonb,
  TRUE
),
(
  NULL,
  'StrongLifts 5x5 - Workout B',
  'Classic StrongLifts 5x5 Program - Workout B. Deadlift performed for 1x5 (one heavy set). Alternate with Workout A.',
  '[
    {
      "name": "Barbell Squat",
      "exercise_type": "strength",
      "sets": 5,
      "reps": 5,
      "weight": 60,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Squat to parallel or below. Keep chest up, drive through heels."
    },
    {
      "name": "Overhead Press",
      "exercise_type": "strength",
      "sets": 5,
      "reps": 5,
      "weight": 30,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Press bar overhead in straight line. Lock elbows at top."
    },
    {
      "name": "Deadlift",
      "exercise_type": "strength",
      "sets": 1,
      "reps": 5,
      "weight": 80,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "ONE WORKING SET ONLY. Most taxing exercise. Add 5kg each workout. Neutral spine, drive through heels."
    }
  ]'::jsonb,
  TRUE
),

-- PUSH/PULL/LEGS SPLIT (Best for hypertrophy and advanced trainees)
(
  NULL,
  'PPL - Push Day',
  'Push/Pull/Legs Split - Push Day. Targets chest, shoulders, and triceps. One of the most effective splits for muscle building.',
  '[
    {
      "name": "Bench Press",
      "exercise_type": "strength",
      "sets": 4,
      "reps": 8,
      "weight": 60,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Primary chest builder. Full range of motion."
    },
    {
      "name": "Seated Dumbbell Shoulder Press",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 10,
      "weight": 22,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Primary shoulder builder. Press to full lockout."
    },
    {
      "name": "Incline Dumbbell Press",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 10,
      "weight": 25,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Targets upper chest. 30-45 degree incline."
    },
    {
      "name": "Lateral Raises",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 15,
      "weight": 10,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Shoulder width. Raise to shoulder height."
    },
    {
      "name": "Triceps Pressdowns",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 12,
      "weight": 25,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Keep elbows stationary. Full extension."
    },
    {
      "name": "Overhead Triceps Extension",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 12,
      "weight": 15,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Targets long head of triceps."
    }
  ]'::jsonb,
  TRUE
),
(
  NULL,
  'PPL - Pull Day',
  'Push/Pull/Legs Split - Pull Day. Targets back and biceps. Essential for balanced physique development.',
  '[
    {
      "name": "Bent-over Barbell Row",
      "exercise_type": "strength",
      "sets": 4,
      "reps": 8,
      "weight": 60,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Primary back builder. Pull to lower chest, squeeze shoulder blades."
    },
    {
      "name": "Pull-ups",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 8,
      "weight": 0,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "King of back exercises. Full extension at bottom, chin over bar at top. Add weight when doing 10+ reps."
    },
    {
      "name": "Barbell Shrugs",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 12,
      "weight": 60,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Trap development. Shrug straight up, no rolling."
    },
    {
      "name": "Face Pulls",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 15,
      "weight": 15,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Rear delts and shoulder health. Pull to face level, external rotation."
    },
    {
      "name": "Barbell Curl",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 10,
      "weight": 30,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Primary bicep builder. No swinging, control the weight."
    },
    {
      "name": "Hammer Curls",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 12,
      "weight": 15,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Targets brachialis. Neutral grip throughout."
    }
  ]'::jsonb,
  TRUE
),
(
  NULL,
  'PPL - Leg Day',
  'Push/Pull/Legs Split - Leg Day. Comprehensive lower body workout for quads, hamstrings, glutes, and calves.',
  '[
    {
      "name": "Back Squats",
      "exercise_type": "strength",
      "sets": 4,
      "reps": 8,
      "weight": 80,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "King of leg exercises. Squat to parallel or below. Keep chest up."
    },
    {
      "name": "Romanian Deadlifts",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 10,
      "weight": 60,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Primary hamstring builder. Focus on stretch at bottom."
    },
    {
      "name": "Leg Press",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 12,
      "weight": 120,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Quad builder. Full range of motion."
    },
    {
      "name": "Leg Curls",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 12,
      "weight": 40,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Hamstring isolation. Control the negative."
    },
    {
      "name": "Calf Raises",
      "exercise_type": "strength",
      "sets": 4,
      "reps": 15,
      "weight": 60,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Full stretch at bottom, squeeze at top."
    },
    {
      "name": "Hanging Leg Raises",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 12,
      "weight": 0,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Core strength. Raise knees to chest, control descent."
    }
  ]'::jsonb,
  TRUE
),

-- HIIT WORKOUTS (Research shows 2-3x per week optimal for fat loss)
(
  NULL,
  'HIIT Circuit - Fat Burner',
  'High-Intensity Circuit Training for maximum calorie burn. 40 seconds work, 20 seconds rest. Repeat 4-5 rounds. Best for fat loss.',
  '[
    {
      "name": "Burpees",
      "exercise_type": "functional",
      "sets": 4,
      "reps": null,
      "weight": 0,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "40 seconds all-out effort, 20 seconds rest. Full body movement."
    },
    {
      "name": "Kettlebell Swings",
      "exercise_type": "strength",
      "sets": 4,
      "reps": null,
      "weight": 16,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "40 seconds continuous swings. Hip hinge movement, explosive power."
    },
    {
      "name": "Jump Squats",
      "exercise_type": "functional",
      "sets": 4,
      "reps": null,
      "weight": 0,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "40 seconds max effort. Explosive power, soft landing."
    },
    {
      "name": "Mountain Climbers",
      "exercise_type": "functional",
      "sets": 4,
      "reps": null,
      "weight": 0,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "40 seconds fast pace. Keep core tight, shoulders stable."
    },
    {
      "name": "Battle Ropes",
      "exercise_type": "cardio",
      "sets": 4,
      "reps": null,
      "weight": 0,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "40 seconds continuous waves. Full body engagement."
    }
  ]'::jsonb,
  TRUE
),
(
  NULL,
  'HIIT Cardio - Running Intervals',
  '20-minute sprint interval workout. Research-backed for fat loss and cardiovascular fitness. Burns same calories as 40-60 min steady cardio.',
  '[
    {
      "name": "Sprint Intervals",
      "exercise_type": "cardio",
      "sets": null,
      "reps": null,
      "weight": null,
      "weight_unit": "kg",
      "duration_minutes": 20,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Warm up 5 min. Then: 30 seconds all-out sprint, 90 seconds jog recovery. Repeat 8-10 times. Cool down 5 min."
    }
  ]'::jsonb,
  TRUE
),

-- FULL BODY WORKOUTS (Great for beginners and 3x/week schedule)
(
  NULL,
  'Full Body Beginner',
  'Perfect starter program for beginners. Hits all major muscle groups 3x per week. Focus on form over weight.',
  '[
    {
      "name": "Goblet Squat",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 12,
      "weight": 16,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Hold dumbbell at chest. Easier to learn than barbell squat."
    },
    {
      "name": "Dumbbell Bench Press",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 10,
      "weight": 20,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Great for beginners. Better range of motion than barbell."
    },
    {
      "name": "Dumbbell Rows",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 10,
      "weight": 20,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Single arm or both. Pull to hip, squeeze at top."
    },
    {
      "name": "Dumbbell Shoulder Press",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 10,
      "weight": 12,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Press overhead, full lockout at top."
    },
    {
      "name": "Romanian Deadlift",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 10,
      "weight": 40,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Hamstrings and lower back. Focus on form."
    },
    {
      "name": "Plank",
      "exercise_type": "strength",
      "sets": 3,
      "reps": null,
      "weight": 0,
      "weight_unit": "kg",
      "duration_minutes": 1,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Hold 60 seconds. Keep body straight, core tight."
    }
  ]'::jsonb,
  TRUE
),

-- WEIGHT LOSS FOCUSED
(
  NULL,
  'Metabolic Conditioning',
  'Combines strength and cardio for maximum calorie burn. Perfect for weight loss. Minimal rest between exercises.',
  '[
    {
      "name": "Thrusters (Squat to Press)",
      "exercise_type": "functional",
      "sets": 4,
      "reps": 12,
      "weight": 20,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Full body movement. Squat then press overhead. High calorie burn."
    },
    {
      "name": "Renegade Rows",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 10,
      "weight": 15,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Plank position, row each arm. Core stability and back strength."
    },
    {
      "name": "Box Jumps",
      "exercise_type": "functional",
      "sets": 3,
      "reps": 10,
      "weight": 0,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Explosive power. Step down carefully. High intensity."
    },
    {
      "name": "Kettlebell Clean and Press",
      "exercise_type": "functional",
      "sets": 3,
      "reps": 8,
      "weight": 16,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Full body power movement. Clean to shoulder, press overhead."
    },
    {
      "name": "Rowing Machine",
      "exercise_type": "cardio",
      "sets": 1,
      "reps": null,
      "weight": null,
      "weight_unit": "kg",
      "duration_minutes": 10,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Finish with steady pace rowing. 85% effort for calorie burn."
    }
  ]'::jsonb,
  TRUE
),

-- CORE & ABS
(
  NULL,
  'Core Strength & Stability',
  'Comprehensive core workout for abs, obliques, and lower back. Essential for all fitness goals.',
  '[
    {
      "name": "Planks",
      "exercise_type": "strength",
      "sets": 3,
      "reps": null,
      "weight": 0,
      "weight_unit": "kg",
      "duration_minutes": 1,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Hold 60 seconds. Foundation of core strength."
    },
    {
      "name": "Russian Twists",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 20,
      "weight": 10,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "20 reps each side. Targets obliques."
    },
    {
      "name": "Hanging Leg Raises",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 12,
      "weight": 0,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Lower abs. Control the descent. Bend knees if needed."
    },
    {
      "name": "Cable Woodchops",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 12,
      "weight": 15,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Rotational core strength. 12 each side."
    },
    {
      "name": "Ab Wheel Rollouts",
      "exercise_type": "strength",
      "sets": 3,
      "reps": 10,
      "weight": 0,
      "weight_unit": "kg",
      "duration_minutes": null,
      "distance": null,
      "distance_unit": "km",
      "speed": null,
      "calories": null,
      "resistance_level": null,
      "incline": null,
      "notes": "Advanced core exercise. From knees if needed."
    }
  ]'::jsonb,
  TRUE
);

-- Update database types (this will be reflected when you regenerate types)
COMMENT ON COLUMN workout_templates.is_public IS 'Whether this template is available to all users (system templates)';
COMMENT ON COLUMN workout_templates.user_id IS 'User who created the template. NULL for system templates.';
