'use client'

import Link from 'next/link'
import { redirect } from 'next/navigation'
import Image from 'next/image'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { getUser } from '@/lib/auth/actions'
import { Dumbbell, TrendingUp, Target, Sparkles } from 'lucide-react'
import { useEffect, useState } from 'react'

export default function Home() {
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function checkUser() {
      const currentUser = await getUser()
      if (currentUser) {
        redirect('/dashboard')
      }
      setLoading(false)
    }
    checkUser()
  }, [])

  if (loading) {
    return null
  }
  const features = [
    {
      icon: Sparkles,
      title: 'AI-Powered Plans',
      description: 'Get personalized workout plans generated by AI based on your goals',
      gradient: 'from-purple-500 to-pink-500',
    },
    {
      icon: Dumbbell,
      title: 'Track Workouts',
      description: 'Log your exercises, sets, reps, and weights with ease',
      gradient: 'from-blue-500 to-cyan-500',
    },
    {
      icon: TrendingUp,
      title: 'Visualize Progress',
      description: 'See your gains with beautiful charts and analytics',
      gradient: 'from-orange-500 to-red-500',
    },
    {
      icon: Target,
      title: 'Set Goals',
      description: 'Create and track fitness goals to stay motivated',
      gradient: 'from-green-500 to-emerald-500',
    },
  ]

  return (
    <div className="flex min-h-screen flex-col">
      {/* Hero Section with Background Image */}
      <section className="relative min-h-[90vh] flex items-center justify-center overflow-hidden">
        {/* Background Image with Overlay */}
        <div className="absolute inset-0 z-0">
          <Image
            src="/hero-health.jpg"
            alt="Health and wellness lifestyle"
            fill
            className="object-cover brightness-50"
            priority
            quality={80}
          />
          <div className="absolute inset-0 bg-gradient-to-br from-black/70 via-black/50 to-black/70" />
        </div>

        {/* Hero Content */}
        <div className="container relative z-10 mx-auto max-w-6xl px-4 py-20 text-center">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full bg-primary/20 px-4 py-2 text-sm font-medium text-primary-foreground backdrop-blur-sm">
            <Sparkles className="h-4 w-4" />
            Your AI-Powered Health & Wellness Companion
          </div>
          <h1 className="mb-6 text-5xl font-bold tracking-tight text-white sm:text-6xl md:text-7xl lg:text-8xl">
            Transform Your{' '}
            <span className="block bg-gradient-to-r from-blue-400 via-purple-400 to-pink-400 bg-clip-text text-transparent">
              Health Journey
            </span>
          </h1>
          {/* <p className="mx-auto mb-10 max-w-2xl text-lg text-gray-200 sm:text-xl md:text-2xl">
            Track workouts, monitor nutrition, visualize progress, and achieve your wellness goals holistically
          </p> */}
          <div className="flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
            <Button size="lg" className="w-auto text-base font-semibold shadow-lg shadow-primary/50 transition-all hover:scale-105 hover:shadow-xl hover:shadow-primary/50" asChild>
              <Link href="/signup">
                Get Started Free <span className="ml-2">→</span>
              </Link>
            </Button>
            <Button
              size="lg"
              variant="outline"
              className="w-auto border-2 border-white/30 bg-white/10 text-base font-semibold text-white backdrop-blur-sm transition-all hover:scale-105 hover:bg-white/20"
              asChild
            >
              <Link href="/login">Sign In</Link>
            </Button>
          </div>
        </div>

        {/* Scroll Indicator */}
        <button
          onClick={() => {
            document.getElementById('features-section')?.scrollIntoView({ behavior: 'smooth' })
          }}
          className="absolute bottom-8 left-1/2 z-10 -translate-x-1/2 animate-bounce cursor-pointer transition-opacity hover:opacity-80"
          aria-label="Scroll to features"
        >
          <div className="h-10 w-6 rounded-full border-2 border-white/30">
            <div className="mx-auto mt-2 h-2 w-2 animate-pulse rounded-full bg-white" />
          </div>
        </button>
      </section>

      {/* Features Section */}
      <section id="features-section" className="bg-gradient-to-b from-background to-muted/30 px-4 py-24">
        <div className="container mx-auto max-w-6xl">
          <div className="mb-16 text-center">
            <h2 className="mb-4 text-4xl font-bold sm:text-5xl">
              Everything You Need to{' '}
              <span className="bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                Succeed
              </span>
            </h2>
            <p className="mx-auto max-w-2xl text-lg text-muted-foreground">
              Powerful features designed to help you track, analyze, and achieve your fitness goals
            </p>
          </div>
          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
            {features.map((feature) => {
              const Icon = feature.icon
              return (
                <Card
                  key={feature.title}
                  className="group relative overflow-hidden border-2 transition-all hover:scale-105 hover:shadow-2xl"
                >
                  <CardContent className="pt-8">
                    <div className={`mb-4 inline-flex rounded-2xl bg-gradient-to-br ${feature.gradient} p-3 shadow-lg transition-transform group-hover:scale-110`}>
                      <Icon className="h-6 w-6 text-white" />
                    </div>
                    <h3 className="mb-3 text-xl font-bold">{feature.title}</h3>
                    <p className="text-muted-foreground">{feature.description}</p>
                  </CardContent>
                  <div className={`absolute inset-x-0 bottom-0 h-1 bg-gradient-to-r ${feature.gradient} transition-transform group-hover:h-2`} />
                </Card>
              )
            })}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="relative overflow-hidden px-4 py-24">
        <div className="absolute inset-0 bg-gradient-to-br from-blue-600 via-purple-600 to-pink-600 opacity-10" />
        <div className="container relative mx-auto max-w-4xl text-center">
          <div className="rounded-3xl border-2 border-primary/20 bg-gradient-to-br from-primary/5 to-purple-500/5 p-12 backdrop-blur-sm">
            <h2 className="mb-4 text-4xl font-bold sm:text-5xl">
              Ready to Transform Your Health?
            </h2>
            <p className="mb-8 text-lg text-muted-foreground sm:text-xl">
              Join thousands of users tracking their progress and achieving their wellness goals
            </p>
            <Button
              size="lg"
              className="text-base font-semibold shadow-lg shadow-primary/50 transition-all hover:scale-105 hover:shadow-xl hover:shadow-primary/50"
              asChild
            >
              <Link href="/signup">
                Start Your Journey Today <span className="ml-2">→</span>
              </Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t bg-muted/50 px-4 py-8">
        <div className="container mx-auto max-w-6xl text-center text-sm text-muted-foreground">
          <p>&copy; {new Date().getFullYear()} GoodHealth. Your health journey starts here.</p>
        </div>
      </footer>
    </div>
  )
}
